services:
  - type: web
    name: talkerybot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python custom_registration.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
